author:
  name: João Campinhos
  email: joao@campinhos.pt
url: http://campinhos.pt
title: João Campinhos
description: João Campinhos' Blog
permalink: /blog/:title.html
exclude: ["gulpfile.babel.js", "package.json", "README.md", "assets", "node_modules", "CNAME"]
